# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
    # Ignore all patch updates, manage these manually.
    # Note: Security updates will still come through.
    - dependency-name: "*"
      update-types: ["version-update:semver-patch"]
    # Ignore webpack updates; Nuxt 2 only supports webpack <5
    - dependency-name: "webpack"
      versions: [">=5.0"]
    # Ignore v-calendar 3.x updates; Nuxt 2 only supports v-calendar 2.x
    - dependency-name: "v-calendar"
      versions: [">=3.0"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
