# Convert old environment variables to new ones
export NITRO_PUBLIC_API_HOST=${API_HOST}
export NITRO_PUBLIC_API_PROTOCOL=${API_PROTOCOL}

export NITRO_PUBLIC_MANAGE_ACCOUNT_URL=${MANAGE_ACCOUNT_URL}
export NITRO_PUBLIC_DEPLOYMENT_ENV=${DEPLOYMENT_ENV}
export NITRO_PUBLIC_SENTRY_CONFIG_ENVIRONMENT=${DEPLOYMENT_ENV}

export NITRO_PUBLIC_OKTA_ISSUER=${OAUTH_ISSUER}
export NITRO_PUBLIC_OKTA_CLIENT_ID=${APP_CLIENT_ID}

node .output/server/index.mjs
