name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      deployment_env:
        description: "Deployment environment"
        default: "staging"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
      
      - name: Install with Yarn
        run: yarn install

      - name: Lint
        run: yarn lint

  publish:
    runs-on: ubuntu-latest
    needs: test

    environment: ${{github.event.inputs.deployment_env}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/renalreg/ukrdc-nuxt:${{github.event.inputs.deployment_env}}
