name: Run Tests

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
      
      - name: Install with Yarn
        run: yarn install

      - name: Lint
        run: yarn lint
